import flet as ft
import sounddevice as sd
import soundfile as sf
import numpy as np
from datetime import datetime
import whisper
import threading
import ollama
import pyperclip

# Load Whisper model once at startup
print("Loading Whisper model...")
whisper_model = whisper.load_model("base")
print("✅ Whisper ready!")

def save_notes_txt(transcript, notes, filename_base):
    """Save notes to a text file"""
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    content = f"""
{'='*60}
MEETING NOTES
{'='*60}
Date: {timestamp}
Recording: {filename_base}

{'='*60}
TRANSCRIPT:
{'='*60}
{transcript}

{'='*60}
AI GENERATED NOTES:
{'='*60}
{notes}

{'='*60}
Generated by Meeting Notes App
{'='*60}
"""
    
    notes_filename = f"notes_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    with open(notes_filename, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return notes_filename

def main(page: ft.Page):
    page.title = "Meeting Notes App"
    page.padding = 20
    page.window_width = 700
    page.window_height = 850
    
    # Recording state
    is_recording = False
    frames = []
    sample_rate = 16000
    stream = None
    
    # Storage for current session
    current_transcript = ""
    current_notes = ""
    current_filename = ""
    
    # UI Components
    status = ft.Text("Ready to record", size=18, weight=ft.FontWeight.BOLD)
    record_btn = ft.ElevatedButton(
        "🎤 Start Recording",
        width=200,
        height=60
    )
    
    transcript_text = ft.Text(
        "",
        size=13,
        selectable=True,
        width=650
    )
    
    notes_text = ft.Text(
        "",
        size=13,
        selectable=True,
        width=650
    )
    
    progress = ft.ProgressBar(visible=False, width=650)
    progress_text = ft.Text("", size=12, italic=True)
    
    # Export buttons - Always visible but start disabled
    export_txt_btn = ft.ElevatedButton(
        "💾 Export as TXT",
        icon=ft.Icons.SAVE,
        disabled=True
    )
    
    copy_btn = ft.ElevatedButton(
        "📋 Copy to Clipboard",
        icon=ft.Icons.COPY,
        disabled=True
    )
    
    export_buttons = ft.Row([export_txt_btn, copy_btn], spacing=10)
    
    file_list = ft.Column()
    
    # Export button handlers
    def export_txt_click(e):
        if current_notes:
            saved_file = save_notes_txt(current_transcript, current_notes, current_filename)
            status.value = f"✅ Exported to {saved_file}"
            page.update()
    
    def copy_click(e):
        if current_notes:
            full_text = f"TRANSCRIPT:\n{current_transcript}\n\nNOTES:\n{current_notes}"
            pyperclip.copy(full_text)
            status.value = "✅ Copied to clipboard!"
            page.update()
    
    export_txt_btn.on_click = export_txt_click
    copy_btn.on_click = copy_click
    
    def generate_notes(transcript):
        nonlocal current_transcript, current_notes
        
        progress_text.value = "🤖 AI is generating meeting notes..."
        page.update()
        
        prompt = f"""You are a meeting notes assistant. Analyze this transcript and create structured notes.

Transcript:
{transcript}

Generate notes in this format:
📋 SUMMARY: (2-3 sentences)

🔑 KEY POINTS:
- Point 1
- Point 2

✅ DECISIONS MADE:
- Decision 1

📝 ACTION ITEMS:
- Task 1

➡️ NEXT STEPS:
- Next step 1

Be concise and clear."""
        
        response = ollama.chat(model='llama3.2', messages=[
            {'role': 'user', 'content': prompt}
        ])
        
        current_transcript = transcript
        current_notes = response['message']['content']
        
        notes_text.value = current_notes
        status.value = "✅ Meeting notes ready! Use buttons below to export."
        progress.visible = False
        progress_text.value = ""
        
        # Enable export buttons
        export_txt_btn.disabled = False
        copy_btn.disabled = False
        
        page.update()
    
    def transcribe_audio(filename):
        status.value = "🎯 Transcribing audio..."
        progress.visible = True
        progress_text.value = "Converting speech to text..."
        page.update()
        
        # Load audio properly
        audio_data, sr = sf.read(filename)
        audio_data = audio_data.astype(np.float32).flatten()
        
        if sr != 16000:
            from scipy import signal
            audio_data = signal.resample(audio_data, int(len(audio_data) * 16000 / sr))
        
        result = whisper_model.transcribe(audio_data, fp16=False, language="english")
        
        transcript_text.value = result["text"]
        progress_text.value = "✅ Transcription complete!"
        page.update()
        
        # Generate notes from transcript
        generate_notes(result["text"])
    
    def toggle_recording(e):
        nonlocal is_recording, frames, stream, current_filename
        
        if not is_recording:
            # START RECORDING
            is_recording = True
            frames = []
            transcript_text.value = ""
            notes_text.value = ""
            
            # Disable export buttons when starting new recording
            export_txt_btn.disabled = True
            copy_btn.disabled = True
            
            status.value = "🔴 Recording... (Click Stop when done)"
            record_btn.text = "⏹️ Stop Recording"
            record_btn.bgcolor = ft.Colors.RED_400
            page.update()
            
            def audio_callback(indata, frame_count, time_info, status_flags):
                if is_recording:
                    frames.append(indata.copy())
            
            stream = sd.InputStream(
                samplerate=sample_rate,
                channels=1,
                callback=audio_callback
            )
            stream.start()
            
        else:
            # STOP RECORDING
            is_recording = False
            
            if stream:
                stream.stop()
                stream.close()
            
            status.value = "💾 Saving recording..."
            page.update()
            
            if len(frames) > 0:
                recording = np.concatenate(frames, axis=0)
                filename = f"meeting_{datetime.now().strftime('%Y%m%d_%H%M%S')}.wav"
                current_filename = filename
                sf.write(filename, recording, sample_rate)
                
                file_list.controls.insert(0, 
                    ft.Text(f"📁 {filename}", size=12)
                )
                
                # Transcribe in background
                threading.Thread(
                    target=transcribe_audio,
                    args=(filename,),
                    daemon=True
                ).start()
                
            else:
                status.value = "❌ No audio recorded"
            
            record_btn.text = "🎤 Start Recording"
            record_btn.bgcolor = None
            page.update()
    
    record_btn.on_click = toggle_recording
    
    page.add(
        ft.Column([
            ft.Text("🎙️ Meeting Notes App", size=32, weight=ft.FontWeight.BOLD),
            ft.Text("Record → Transcribe → AI Notes → Export", size=14, italic=True, color=ft.Colors.GREY_700),
            ft.Divider(),
            
            status,
            progress_text,
            progress,
            ft.Container(height=10),
            
            record_btn,
            ft.Container(height=20),
            
            ft.Text("📝 Transcript:", size=16, weight=ft.FontWeight.BOLD),
            ft.Container(
                content=transcript_text,
                bgcolor=ft.Colors.GREY_100,
                padding=10,
                border_radius=5,
                height=150,
            ),
            
            ft.Container(height=15),
            ft.Text("📋 AI Generated Notes:", size=16, weight=ft.FontWeight.BOLD),
            ft.Container(
                content=notes_text,
                bgcolor=ft.Colors.BLUE_50,
                padding=10,
                border_radius=5,
                height=200,
            ),
            
            ft.Container(height=10),
            export_buttons,
            
            ft.Container(height=20),
            ft.Text("Recent Recordings:", size=14, weight=ft.FontWeight.BOLD),
            file_list,
        ], scroll=ft.ScrollMode.AUTO)
    )

ft.app(target=main)